"""U.S. jurisdictions for corpus matrix (mirror of site us-states.ts)."""
from __future__ import annotations

# Federal first, then 50 states A–Z, DC, territories.
JURISDICTIONS_FULL: tuple[str, ...] = (
    "US",
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "FL",
    "GA",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY",
    "DC",
    "PR",
    "GU",
    "VI",
    "AS",
    "MP",
)

# Priority launch set (kept for --all-states-seed legacy / fast loops).
STATES_SEED_PRIORITY: tuple[str, ...] = ("US", "CA", "NY", "TX", "FL", "IL")

TERRITORIES: tuple[str, ...] = ("PR", "GU", "VI", "AS", "MP")
