# Sync credentials from .env.local (root) to site/.env.local and signalhub/usa/.env
$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent
$master = Join-Path $root ".env.local"

if (-not (Test-Path $master)) {
    Write-Host "Missing .env.local at root. Copy .env.local.example to .env.local"
    exit 1
}

$vars = @{}
Get-Content $master -Encoding UTF8 | ForEach-Object {
    $line = $_.Trim()
    if (-not $line -or $line.StartsWith("#")) { return }
    if ($line -match '^([^=]+)=(.*)$') {
        $vars[$Matches[1].Trim()] = $Matches[2].Trim()
    }
}

$siteKeys = @(
    "NEXT_PUBLIC_APP_URL",
    "SUPABASE_PROJECT_REF",
    "NEXT_PUBLIC_SUPABASE_URL",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY",
    "SUPABASE_URL",
    "SUPABASE_SERVICE_ROLE_KEY",
    "SUPABASE_DB_PASSWORD",
    "NEXT_PUBLIC_WHATSAPP_NUMBER",
    "NEXT_PUBLIC_WHATSAPP_URL",
    "WHATSAPP_URL",
    "TELEGRAM_BOT_TOKEN",
    "TELEGRAM_CHAT_ID",
    "WHATSAPP_VERIFY_TOKEN",
    "PAGAMENTO_WEBHOOK_SECRET",
    "AGENDA_DISPONIVEL",
    "STRIPE_SECRET_KEY",
    "STRIPE_WEBHOOK_SECRET",
    "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY",
    "STRIPE_LINK_ESSENCIAL",
    "STRIPE_LINK_PADRAO",
    "STRIPE_LINK_COMPLETO",
    "GROQ_API_KEY",
    "GROQ_MODEL",
    "ADMIN_EMAIL",
    "GOOGLE_OAUTH_CLIENT_ID",
    "GOOGLE_OAUTH_CLIENT_SECRET",
    "RESEND_API_KEY",
    "RESEND_FROM_EMAIL",
    "FOCUS_NFE_AUTO"
)
$siteLines = @("# Generated by sincronizar-env.ps1", "")
foreach ($k in $siteKeys) {
    if ($vars.ContainsKey($k)) { $siteLines += "$k=$($vars[$k])" }
}
$siteLines | Set-Content (Join-Path $root "site\.env.local") -Encoding UTF8
Write-Host "OK: site\.env.local"

$botKeys = @(
    "GROQ_API_KEY", "GROQ_MODEL", "GROQ_REVISAO",
    "TELEGRAM_BOT_TOKEN", "TELEGRAM_CHAT_ID",
    "REDDIT_SUBREDDITS", "REDDIT_LIMIT",
    "SCAN_INTERVAL_SECONDS", "MAX_ALERTAS_POR_HORA",
    "SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_URL",
    "SUPABASE_SERVICE_ROLE_KEY", "AGENDA_DISPONIVEL"
)
$botLines = @("# Judicial Intelligence Signal Hub (USA)", "")
foreach ($k in $botKeys) {
    if ($vars.ContainsKey($k)) { $botLines += "$k=$($vars[$k])" }
}
$botLines | Set-Content (Join-Path $root "signalhub\usa\.env") -Encoding UTF8
Write-Host "OK: signalhub\usa\.env"
